### PR TITLE
Add check if there is already a maven publication

### LINKED ISSUE #266: Mysterious "maven" publication from nowhere
I'm working on an open source library where I have multiple modules which represent each a single artifact.

Here is my code:

```
publishing.publications {
    ssmlPlugin(MavenPublication) {
        groupId = 'org.rewedigital.voice.dialog'
        artifactId = 'ssml-plugin'
        //...
        pom {
            name = 'dialog'
            description = 'This is the SSML-Builder plugin for Dialog to write voice applications fast.'
            url = 'https://github.com/rewe-digital-incubator/dialog'
            licenses { // ...
```
<sup>[full code](https://github.com/rewe-digital-incubator/dialog/blob/7ea42fa651c2cd4b68cca300f537e496c63a0557/ssml-plugin/build.gradle#L40)</sup>

I'm creating there a custom pom file since I was not sure how to do that with your plugin. In the end here is the partial redundant publish block:

```
publish {
    userOrg = 'rewe-digital'
    groupId = 'org.rewedigital.voice.dialog'
    artifactId = 'ssml-plugin'
    repoName = 'dialog'
    publishVersion = rootProject.ext.versions.core
    desc = 'This is the SSML-Builder plugin for Dialog to write voice applications fast.'
    website = 'https://github.com/rewe-digital-incubator/dialog'
    licences = ['MIT']
    bintrayUser = project.properties['bintray.user']
    bintrayKey = project.properties['bintray.apikey']
    dryRun = false
    publications = ['ssmlPlugin']
}
```

This works fine so far. Just when I reference the "core" module from another module (via `implementation project(":core")`) it keeps crashing in [`DefaultProjectDependencyPublicationResolver`](https://github.com/gradle/gradle/blob/v5.1.1/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/DefaultProjectDependencyPublicationResolver.java#L107) with an exception like this:

> java.lang.UnsupportedOperationException: Publishing is not able to resolve a dependency on a project with multiple publications that have different coordinates.
> Found the following publications in project ':core':
>   - Maven publication 'core' with coordinates org.rewedigital.voice:dialog:1.0 <- correct one!
>   - Maven publication 'maven' with coordinates org.rewedigital.voice:core:1.0 <- does not even exists!

(Please note that this error is from a different module which is not yet pushed, however it is the same error)

For some reasons there is a 'maven' publication which I did not define.

I also tried this workaround:

```
allprojects {
    afterEvaluate { project ->
        project.publishing.publications.forEach { publication ->
            if(publication.name == 'maven') {
                println('hit!')
                project.publishing.publications.remove(publication)
            }
        }
    }
}
```

When I check the `publications` then there is as expected just one, but that gradle task `bintrayUpload` still fails with the error above.

### PR DESCRIPTION
**Pull request by rekire**
This change is intended to fully customize the pom file as you like, by defining your own publication. This should resolve #266

### CODE REVIEW

**Comment by hal9002** [comment]
Can one of the admins review this PR?

**Comment by mr-archano** [comment]
@hal90002 retest this please

**Comment by mr-archano** [comment]
@rekire thanks for the collaboration. I changed the base branch as we use `develop` to accept new features and `master` is used only to do releases.

**Comment by mr-archano** [comment]
@rekire something is weird with this merge. Could you please rebase your branch on latest `develop` and force push?

**Comment by rekire** [comment]
I tried that, I hope it worked. I just saw that you did a force push two hours ago. I hope I didn't break your work.

**Comment by mr-archano** [comment]
It seems ok, thanks @rekire.

I would like to extend this functionality in order to improve configurability. Also we would need to keep things in sync with Android libraries too. But that can wait.
I was thinking that we could just merge this so you will be able to use a snapshot of the plugin (see [instructions](https://github.com/novoda/bintray-release#snapshots)) and solve your issue. what do you think?

**Comment by mr-archano** [comment]
@hal90002 retest this please

**Comment by rekire** [comment]
That sounds fine for me. Just for my curiosity which tasks are open before the next release?

**Comment by mr-archano** [comment]
@rekire there's no milestone defined yet. I was just thinking of improving upon your idea so we could release a more robust yet flexible solution.

**Comment by rekire** [comment]
Everything is fine. Thanks for merging

**Pull request merged**
