### PR TITLE
Gradle 6.x support

### LINKED ISSUE #298: Need gradle 6.0 support

### PR DESCRIPTION
**Pull request by marandaneto**
Fix #298

### CODE REVIEW

**Comment by hal9002** [comment]
Can one of the admins review this PR?

**Comment by radzio** [comment]
Any updates? It would be great to have a release with this fix.

**Comment by marandaneto** [comment]
hey @zegnus and @Mecharyry would you mind having a look at it? :) thanks.

**Comment by bkorda** [comment]
Hey, we really need this update.

**Comment by ooftf** [comment]
publish to mavenLocal don't work when implementation

**Pull request closed without merging**
