### PR TITLE
Add Plugin ID , change from bintray-release to com.novoda.bintray-release

### PR DESCRIPTION
**Pull request by friedger**
This PR adds the plugin id to a namespaced version (com.novoda.bintray-release)
The old id is still preserved.

This is to follow the guidelines at https://docs.gradle.org/current/userguide/custom_plugins.html#N16E5C

When this is merged a new version should be released ASAP to make bintray match the website.

### CODE REVIEW

**Comment by friedger** [comment]
This fixes #57

**Comment by blundell** [comment]
this also breaks the upgrade path for anyone using this plugin? api breaking change

**Comment by friedger** [comment]
This does not break the upgrade path, as both ids are still published.

**Comment by xrigau** [comment]
:+1: seems legit

**Comment by xrigau** [comment]
:shipit:

**Comment by xrigau** [comment]
@friedger do you want to do the release?

**Pull request merged**
