### PR TITLE
Ci shell script

### PR DESCRIPTION
**Pull request by StefMa**
Same as #173 but with fixed tests...
But I can't reopen it somehow.. So created a new PR 😄

### CODE REVIEW

**Comment by tasomaniac** [comment]
Hmm, the CI job is public now actually. But still it is a nice improvement.

**Comment by StefMa** [comment]
Yes, but with such a script we (the project) can control how to test the code. It is also versioned with git.

Have you changed the Jenkins job configuration that it runs the shell script?

**Comment by tasomaniac** [comment]
Just did it now. #174 is building with the script now.

**Comment by tasomaniac** [comment]
Btw, Instead of a shell script, it is also possible to create gradle tasks. 

```
  task ciPrb(type: GradleBuild) {
    group = 'verification'
    description = 'Task executed for Jenkins PRB builds'
    tasks =  ['clean', `build`, `bintrayUpload`]
    startParameter.projectProperties = [dryRun: true]
    startParameter.logLevel = LogLevel.INFO
  }
```

**Comment by StefMa** [comment]
Oh wow. Didn't know that. Nice thing!

**Pull request merged**
