### PR TITLE
Extract artifacts

### PR DESCRIPTION
**Pull request by StefMa**
This is a "follow up" of #127 
But this time only as a module (instead of a new project).

Currently the tests are broken. I work on that 👍 

Basically I've only created a new module with the classes which are responsible for the aar generation, pom and stuff like that.
These files will be included in the "core"-jar. Each transitive dependencies will not be included. 
(You can check the jar output if you like. There you will see that just the files (not a JAR) will be included into the core-jar).

### CODE REVIEW

**Comment by StefMa** [comment]
WTHM? :D

**Comment by StefMa** [comment]
ok to test

**Comment by StefMa** [comment]
@ataulm @blundell whats going on here? 😄 
Can someone fix the @hal90002 bot please?  🙏

**Comment by blundell** [comment]
Hal's mad

**Comment by blundell** [comment]
https://ci.novoda.com/job/bintray-release-prb/33/console

screen shot 2017-12-05 at 11 04 26

**Comment by ataulm** [comment]
>Currently the tests are broken. I work on that 👍

@StefMa Hal will not allow us to merge to master with broken tests

**Comment by StefMa** [comment]
I am fine with that rule. But is it needed that the PR get closed? 🤔

**Comment by blundell** [comment]
yes :-) broken tests are the authors responsibility, therefore PR's are closed to save other peoples time until the PR can stay open.

**Comment by StefMa** [comment]
I don't really get the issue.
It seems that the testKit or the java-gradle-plugin don't really recognizes the module :/

I've tried different things without success.
This will work:
```diff
- configurations.compileOnly.extendsFrom(configurations.extraLibs)
+ configurations.compile.extendsFrom(configurations.extraLibs)
```
But we don't want to have the `extraLibs` as a compile dependencies. So that is not a solution.
I've also tried to add `testCompile project(':artifacts')` which don't work.

I bet there is something with the classpath or so... 
I'm not really deep into gradle-testing so I need a little bit help here.
Can maybe someone look over it?
@zoonooz ?

**Comment by zoonooz** [comment]
**For the `TestBintrayUploadTask`**,
As the structure changed, need to add one more level in project path string.
```groovy
private File getAbsoluteDirectoryOfOurProjectBase() {
    def fileDir = getClass().protectionDomain.codeSource.location.path
    return new File(fileDir + "../../../../..")
}
```
as well as task name checking
```groovy
assert successfulTaskPaths.contains(":core:bintrayUpload")
```

**For the generating test cases**
As you use `compileOnly` the Artifact classes will not be added to the test classpath and using `testCompile` will not help as well because it will be there just only when compiling the test classes.

Actually, I don't really know what's the goal here but I don't think it makes sense if you want to separate the Artifact classes but manually put them back inside the jar, it just breaks the test. I think if you want to use `compileOnly` then it is the consumer's responsibility to add those classes when they use the plugin.

**Comment by StefMa** [comment]
Hey @zoonooz thanks for the help.
The TestBintrayUploadTask is fixed 👍 

The idea raised here: https://github.com/novoda/bintray-release/pull/127#issuecomment-341667381
We (at grandcentrix) need a artifactory-release (let's call it like that).
And we can use the artifacts generation code from the bintray-release and build the artifactory in top...
We decided to make a separate to module (but put it into the lib) because we don't want that novoda has the "controll" over the release of the artifacts-release.
bintray-release should work normally like before. But the artifactory-release needs the artifacts code...

You know what I mean? :D

**Comment by zoonooz** [comment]
@StefMa maybe.. 😅  So I think we have to add those artifact classes back to the classpath. Not sure this is the good way though.
```groovy
sourceSets {
    main {
        runtimeClasspath += project(':artifacts').sourceSets.main.runtimeClasspath
    }
}
```

**Comment by StefMa** [comment]
ok to tests

**Comment by StefMa** [comment]
ok to test

**Comment by StefMa** [comment]
I thought about this solution a while and I really don't like it...
I've also asked a question int the [gradle forums](https://discuss.gradle.org/t/how-to-share-code-between-plugins/25293/4) where they suggest to use a independent third lib..
But that is what novoda don't like, right? 🤔 

So to be honest, I really don't know how to solve it for now...

**Pull request closed without merging**
