### PR TITLE
Update Gradle version to 4.2.1

### PR DESCRIPTION
**Pull request by Werb**
update and support new dependencies command implementation and api

### CODE REVIEW

**Comment by hal9002** [comment]
Can one of the admins review this PR?

**Comment by StefMa** [comment]
"it's working" with 4.2.1. But if you take a look into https://github.com/novoda/bintray-release/issues/138 it would be great if don't use a gradle version higher than 4.1

**Comment by StefMa** [comment]
Hi, why have you closed the PR?
You are very welcome to create a PR here
https://github.com/StefMa/bintray-release 🙃
But please with 4.1 👍

**Comment by blundell** [comment]
For anyone reading this PR - the changes did not fix the issue, it just bumped the version without checking.

**Pull request closed without merging**
