### PR TITLE
Extract AndroidArtifacts

### PR DESCRIPTION
**Pull request by StefMa**
Hey guys,

as you probably now the current `bintray-relase` do two things:
1. It prepares and create the artifacts and publishing stuff
2. It gives the user a simple wrapper about the bintray plugin

Because we use internally an artifactory I've used this plugin and put everything to work with artifactory on top of it (this isn't public available 😉). 
So our internally plugin can three things. The same like above plus the ability to have a simple wrapper for the artifactory plugin.

Some great colleague have the idea to split it up. 
So that we end in three different plugins:
* One for preparing and creating artifacts
* One for a simple wrapper over the bintray plugin
* One for a simple wrapper over the artifactory plugin

Èt voila. Let me introduce the [AndroidArtifacts plugin](https://github.com/StefMa/AndroidArtifacts). This is the *base plugin* for the other two but can also be used as a standalone plugin. 

The ArtifactoryPublish is available [here](https://github.com/StefMa/ArtifactoryPublish) and can be used to publish the artifacts to artifactory.

Last but not least I've created this PR to use the `AndroidArtifacts` as  base.
To show that everything works correctly I've created a test with ThirtyInch.
The changes are [here](https://github.com/grandcentrix/ThirtyInch/compare/master...StefMa:testing_stefma_plugin).
The result is on [my bintray](https://bintray.com/stefma/maven/ThirtyInch#files/net/grandcentrix/thirtyinch).

### Some more infos:
I've removed the deprecated `version` and `description` strings from the `extension`. 
`version` is now used inside the `AndroidArtifacts` plugin and I don't want to start with a depcrecated identifier from the beginning. That is the reason why I've removed it :)
`description` can be - if you like - easily added again. Because it is used by the bintray-plugin and not by the base plugin.

I haven't tested it yet. But probably you can't use two (or more) plugins in **one** project. It brings no benefit to use the base + one on top plugin (`AndroidArtifacts` & artifactory || bintray). But maybe you want to use artifactory plus the bintray plugin. I think with that config gradle got confused. But I will change the `artifactory` plugin in the future so that we don't get into trouble if someone uses artifactory + bintray...

So yeah. That is from all from my side 👍

### CODE REVIEW

**Comment by stefanhoth** [comment]
Can one of the admins review this PR?

**Comment by StefMa** [comment]
@tasomaniac or @ouchadam can you take a look on it? 🤔 👍 😄

**Comment by tasomaniac** [comment]
Sorry for the late review. The code changes looks good to me. I think the plugin internally is doing the same anyways, right? I'm not the maintainer of the project and I don't know if it really makes sense to make this change within the library considering the plugin you have is still in early stages. 

Also it would be great to add some tests around the refactoring to prove no behavior changes. 

Thanks.

**Comment by StefMa** [comment]
@blundell the "problem" is that I need the same source in my Artifactory plugin. So for me it is just a logical step to have this code in its own lib.

But you are right. It is hard to maintain. If something is broken in the 'base' plugin, we have to fix it there. Make a release, update bintray-release/Artifactory and make a release for both as well...

Currently I have no other idea to share these code rather than have it in its own plugin...

**Comment by passsy** [comment]
The `AndroidArtifacts plugin` could be a module of this repo. If it creates it's own artifact (also published to bintray) we could reuse it in the `Artifactory` plugin. It wouldn't create overhead here and we can reuse it.

**Comment by StefMa** [comment]
Ok, cool idea.
But how do we manage the responsibility of that module?
Since it is available in this repo novoda would be the owner (also the publisher to bintray or somewhere else).
So our `Artifactory` plugin depends on novoda and how fast they are releasing a probably new version of that...

But 👆 
We can also try to implement [shipkit](https://github.com/mockito/shipkit) somehow. This will make a release to bintray automatically after each merge (plus additional benefits). 
But for that we have to switch the CI to travis... 😃

**Comment by passsy** [comment]
Our current plan:
- Make `AndroidArtifacts` a separate module within this repository
- Create a new repo `grandcentrix/artifactory-release` and copy the `AndroidArtifacts` module from here.
- Watch this repo and manually or automated sync changes of the `AndroidArtifacts` module to our artifactory plugin.

In the end we have two standalone projects to publish to bintray and artifactory without hard dependencies.

**Comment by blundell** [comment]
that makes sense to me 👍 

(sorry fore the delay, been on holiday)

**Comment by blundell** [comment]
So next steps on this PR.

I will close it for now. If the changes are made you can reopen. Otherwise a new PR is fine.

**Pull request closed without merging**
