### PR TITLE
adding field to allow GPG Signing on bintray's side

### PR DESCRIPTION
**Pull request by marandaneto**
https://github.com/bintray/gradle-bintray-plugin#GPG_File_Signing

### CODE REVIEW

**Comment by hal9002** [comment]
Can one of the admins review this PR?

**Comment by mr-archano** [comment]
@hal9002 retest this please

**Comment by mr-archano** [comment]
@marandaneto could you please change the base branch to be `develop` instead? As the [doc says](https://github.com/novoda/bintray-release/blob/master/README.md#snapshots), once this is merged a new snapshot release will be available at https://bintray.com/novoda-oss/snapshots/bintray-release

**Comment by Mecharyry** [comment]
hal test this.

**Comment by Mecharyry** [comment]
test this

**Comment by Mecharyry** [comment]
hal test this

**Pull request merged**
