### PR TITLE
Add flavor and buildType specific dependencies to pom

### PR DESCRIPTION
**Pull request by remcomokveld**
**The Problem**
In my previous PR I added support for publishing multi-flavor libraries. When I wanted to use it I had missing transitive dependencies in the generated pom. This was because only 'compile' configuration dependencies were added

**The solution**
By making a AndroidLibrary determine dependencies based on flavors the debugCompile and flavorCompile dependencies are also added to the pom

### CODE REVIEW

**Comment by jjhesk** [comment]
+1

**Comment by remcomokveld** [comment]
Why are you closing this? Did you fix it in another way?

**Comment by takecare** [comment]
@remcomokveld sorry i seem to have closed this by accident (was supposed to be closing on other PR). _reopening._

**Comment by stefanhoth** [comment]
Can one of the admins review this PR?

**Comment by passsy** [comment]
I'd love to have support for multiple buildTypes ❤️

**Comment by mobiledrc** [comment]
I think the fix is very useful for me. Any admins help to review and merge it? thanks

**Comment by blundell** [comment]
@remcomokveld sorry to get round to this so late, could you resolve the conflicts? then I'll take a look

**Comment by blundell** [comment]
please reopen when conflicts are resolved

**Pull request closed without merging**
