### PR TITLE
Prepare release 0.8.1

### PR DESCRIPTION
**Pull request by mr-archano**
Bumps version of the plugin for a new bugfix release. 

Includes some minor tweaks/features:
- #159 Support `override` parameter from [`gradle-bintray-plugin` DSL](https://github.com/bintray/gradle-bintray-plugin/blob/master/README.md#plugin-dsl)
- #160: Fix Android variants evaluation
- #181 Better configuration validation
- #191, #192 Remove deprecated properties
- #202 Support Android `archiveBaseName` property

### CODE REVIEW

**Comment by StefMa** [comment]
Please update the Readme table as well 👍

**Comment by mr-archano** [comment]
What do we need to update in the table @StefMa? I will check the Readme again shortly

**Comment by StefMa** [comment]
I mean the gradle compatibility table
-> https://github.com/novoda/bintray-release#gradle-compatibility

**Comment by steurt** [comment]
@mr-archano I've added a page to the [wiki](https://github.com/novoda/bintray-release/wiki/Configuring-a-custom-Android-artifact-name), describing the support for #202. You could reference that in the release-notes/change-log.

**Comment by StefMa** [comment]
@steurt thanks. 
But see #162.
Wikis are outdated these days :D

**Comment by mr-archano** [comment]
Thanks @StefMa for taking care of the table, it's been crazy busy at work the last couple of days.

@steurt thanks a lot for your contribution, I will add that link to the change log. I agree with @StefMa re: wiki pages in general, and personally I'd prefer to have a folder of documents checked in the repo that can undergo the usual review process and evolve as the code does (I have pushed for the same approach for the other repos I help maintaining for instance).

**Comment by mr-archano** [comment]
@steurt `0.8.1` is [released](https://bintray.com/novoda/maven/bintray-release/0.8.1) to JCenter. Let us know if any issue.

**Pull request merged**
